### ISSUE TITLE
Preview window remains open when searching for processes

### ISSUE THREAD

**Issue by eh8** [lbcnz/fzfx#2]
When running `fzfx ps`, the preview window appears on the right which isn't very helpful. From the screenshots in the README I'm assuming this is not supposed to appear.

I have made no configuration changes from the default `fzf` package installed from Arch. I tried running the command after removing the fzf plugin from oh-my-zsh, deleting any relevant `fzf` lines in my `.zshrc`.

![image](https://user-images.githubusercontent.com/22990581/113824176-7409b000-974d-11eb-9bab-445ab27c735e.png)

**Comment by danisztls** [comment]
Fixed and updated AUR package.
Thanks for reporting.
