### ISSUE TITLE
"fzfx cd" doesn't work if the root config option is set

### ISSUE THREAD

**Issue by d3-X-t3r** [lbcnz/fzfx#5]
I've got `root="$HOME"` configured in my fzfx config file. As a result of this however, `fzfx cd` no longer works as expected. Running `fzfx cd` and selecting the directory only results in the (relative) path printing to the console - it doesn't actually change the directory.

Example in bash - attempting to cd to ~/Games/Diablo2 via fzfx:

```
$ pwd
/home/dexter/Downloads
$ fzfx cd
Games/Diablo2
$ pwd
/home/dexter/Downloads
```

fzfx version: fzfx-git v1.1.3.r1.g7b862da-1
Bash version: 5.1.4(1)-release (x86_64-pc-linux-gnu)
OS: Arch Linux x64

**Comment by se7en-x230** [comment]
Same problem here. Arch Linux

**Comment by danisztls** [comment]
Just released 1.1.4 to fix it.

**Comment by se7en-x230** [comment]
Nope still can't jump to the directory

**Comment by danisztls** [comment]
@se7en-x230 Probably due to some bad tags that I released after.

I just released 1.2. Please try it.

Also I renamed `$root` to `$searchPath` but `$root` is still supported.

**Comment by se7en-x230** [comment]
Sorry still same problem. How can I help to debug?

**Comment by danisztls** [comment]
It is looking like a distribution problem/bug. First we need to ensure we are running the same version. How are you installing it? If via AUR, what helper are you using?

The package on AUR is a continuous release model where the PKGBUILD file is not updated but the helper check for newer tags on upstream and update accordingly.  [paru](https://github.com/Morganamilo/paru) does that but I don't know about other AUR helpers.

Unfortunately there's no `--version` so it would be great if you could clone the repository. You don't have to install it but just check if it work when doing this from inside it:

```sh
cd $(./fzfx cd)
```

I'm running the latest release which is v1.2 with hash 339eb0e0639c1d0acb5ede7a06b5a5cfb391aab2.

**Comment by se7en-x230** [comment]
Initial install was via trizen from AUR.
But as I saw the package was not updated I cloned and ran the setup script.

According to the script it moves the binary into .local/bin.

I renamed that and.ran it from that location just to make sure I run the latest version

**Comment by se7en-x230** [comment]
cd $(./fzfx cd) works ??? but not if I run it fzfx cd

**Comment by d3-X-t3r** [comment]
> cd $(./fzfx cd) works ??? but not if I run it fzfx cd

Same here. fzfx cd doesn't work, but cd $(fzfx cd) works. At least it's grabbing the full path now and not the relative path, so I guess one half of the bug is fixed.

**Comment by danisztls** [comment]
It looks like you two don't have that alias set. Check the README.md. I updated it with further information regarding that.
