### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by se7en-x230** [lbcnz/fzfx#7]
Is it possible to toggle on/off hidden files or at least make them default on?
* most linux files to be edited are . files 
Would it be possible to add cp/mv maybe even cd to a F# keybinding as default editor clipboard ...? 
* That would make the tool more flexible.

very nice tool by the way.

**Comment by danisztls** [comment]
1. Use `fzfx hidden`.
2. In theory, yes! But have to try it to see if it works. Sometimes things tends to conflict in strange ways.

Also you can edit the script or export  `FZF_DEFAULT_OPTS` to change stuff. Feel free to PR things that you find interesting.

**Comment by danisztls** [comment]
@se7en-x230  I'm closing this one as I created related enhancement proposals on #14 and #15.
